path:
  raw_path: ./data/raw/
  processed_path: ./data/processed/
  files_path: ./research/files/


# path:
#   raw_path: ../../data/raw/
#   processed_path: ../../data/processed/
#   files_path: ../../research/files/